version: "3.10"

x-settings:
  &global
  environment:
    - API_TOKEN=${API_TOKEN}
    - ADMIN=${ADMIN}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - PG_NAME=${PG_NAME}
    - PG_USER=${PG_USER}
    - PG_PASSWORD=${PG_PASSWORD}
    - PG_HOST=${PG_HOST}
    - PG_PORT=${PG_PORT}


services:
  db:
    container_name: tg_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    <<: *global

#  bot:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: tgbot
#    restart: always
#    <<: *global
#    ports:
#      - "8000:8000/udp"
#    depends_on:
#      - db

volumes:
  postgres_data:

