[tool.poetry]
name = "telegramshoter"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.21"
python-decouple = "^3.6"
loguru = "^0.6.0"
validators = "^0.20.0"
aioselenium = "^0.0.1"
selenium = "^4.3.0"
pyppeteer = "^1.0.2"
Pillow = "^9.2.0"
click = "^8.1.3"
aiofiles = "^0.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
