name: deploy to production

on:
  push:

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Install black
        run: pip install black
      - name: Checking...
        run: black --check .

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 . --max-line-length=101

  isort:
    name: Isort
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Install isort
        run: pip install isort
      - name: Run isort
        run: isort . --check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      API_TOKEN: 5469389176:AAHzDrJXdWAuvCEBFIbVgaLkfF_ue-K3KEs
      ADMIN: 412199751
      PG_NAME: tgshot
      PG_USER: tgshot
      PG_PASSWORD: tgshot
      PG_HOST: db
      PG_PORT: 5432
      POSTGRES_PASSWORD: tgshot
      POSTGRES_USER: tgshot
      POSTGRES_DB: tgshot
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Build
        run: |
          pip install --upgrade pip poetry
          poetry config virtualenvs.create false
          poetry install --no-dev
          docker-compose up -d db
      - name: Run tests
#        run: pytest -c pyproject.toml
        run: docker ps




