name: deploy to production

on:
  push:

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Install black
        run: pip install black
      - name: Checking...
        run: black --check . --max-line-length=101

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: python:3.10
    env:
      API_TOKEN: 5469389176:AAHzDrJXdWAuvCEBFIbVgaLkfF_ue-K3KEs
      ADMIN: 412199751
      PG_NAME: tgshot
      PG_USER: tgshot
      PG_PASSWORD: tgshot
      PG_HOST: db
      PG_PORT: 5432
      POSTGRES_PASSWORD: tgshot
      POSTGRES_USER: tgshot
      POSTGRES_DB: tgshot
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Build
        run: |
          poetry install --no-dev
          docker-compose up -d db
      - name: Run tests
        run: pytest -c pyproject.toml





