name: deploy to production

on:
  push:
    branches-ignore:
      - master


jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64
      - name: Checkout the latest code
        uses: actions/checkout@v1
      - name: Install black
        run: pip install black
      - name: Checking...
        run: black --check .
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  mypy:
    name: MyPy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64
        - uses: actions/checkout@v2
        - name: Install bandit
          run: pip install mypy
        - name: mypy .




