name: deploy to production

on:
  push:
    branches-ignore:
      - master


jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Install black
        run: pip install black
      - name: Checking...
        run: black --check .
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  mypy:
    name: MyPy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install MyPy
        run: pip install mypy
      - name: Run MyPy
        run: mypy .




